version: '3.8'

services:
  app:
    image: task-management-app:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vivek
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
