apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springBoot.profile | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  JWT_EXPIRATION_MS: {{ .Values.jwt.expirationMs | quote }}
  JWT_ISSUER: {{ .Values.jwt.issuer | quote }}
  JWT_AUDIENCE: {{ .Values.jwt.audience | quote }}
